import {
  BarChart2,
  LogOut,
  Settings,
  Users,
  UserCog,
  Grid2x2Check,
  ShoppingBag,
  Package,
  ClipboardList,
  FileText,
} from "lucide-react";

export const sidebarItems = [
  {
    name: "Overview",
    icon: BarChart2,
    color: "#6366f1",
    href: "/",
    permission: null,
  },
  {
    name: "Roles",
    icon: UserCog,
    color: "#8B5CF6",
    href: "/roles",
    permission: null,
  },
  {
    name: "Users",
    icon: Users,
    color: "#EC4899",
    href: "/users",
    permission: null,
  },
  {
    name: "Departamentos",
    icon: Grid2x2Check,
    color: "#F59E0B",
    href: "/departamentos",
    permission: null,
  },
  {
    name: "Productos",
    icon: ShoppingBag,
    color: "#34D399",
    href: "/productos",
    permission: null,
  },
  {
    name: "Materiales",
    icon: Package,
    color: "#F472B6",
    href: "/materiales",
    permission: null,
  },
  {
    name: "Órdenes",
    icon: ClipboardList,
    color: "#FBBF24",
    href: "/ordenes",
    permission: null,
  },
  {
    name: "Reportes",
    icon: FileText,
    color: "#60A5FA",
    href: "/reportes",
    permission: null,
  },
  {
    name: "Settings",
    icon: Settings,
    color: "#6EE7B7",
    href: "/settings",
    permission: null,
  },
  {
    name: "Logout",
    icon: LogOut,
    color: "#6EE7B7",
    href: "#",
    permission: null,
  },
];
